### PR TITLE
Do not shade "com.sun.msv.driver.textui" as it drags in a lot of

### LINKED ISSUE #96: woodstox-core.jar 6.0.2 uses JDK-11 removed internal APIs
- The latest version of woodstox-core.jar 6.0.2 uses below JDK-11 removed internal APIs:

**jdeps scan report:** 
digraph "woodstox-core-6.0.2.jar" {
"com.ctc.wstx.shaded.msv_core.driver.textui.Driver" -> "com.sun.org.apache.xml.internal.resolver.Catalog (JDK internal API (**JDK removed internal API))**";
"com.ctc.wstx.shaded.msv_core.driver.textui.Driver" -> "com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver (**JDK internal API (JDK removed internal API**))";
}

We are migrating our project to Java 11, Can someone please have a look into this issue?

### PR DESCRIPTION
**Pull request by kwin**
unnecessary transitive dependencies

This fixes #96

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Sounds good; I'll have a look when I get a chance and hopefully get improved version released as 6.1.0.

**Comment by cowtowncoder** [comment]
Turns out this caused a gnarly incompatibility due to `com/sun/msv/driver/textui/Debug` being referenced from some other MSV-core class. Checked in what I think is the fix, essentially only leaving that class; this seems to produce something where validator still works.

@kwin do you think you could check out from `master` that dependencies are still pruned as expected? I can then proceeded with 6.1.1 patch release.

**Comment by kwin** [comment]
I checked just now with 6.1.1-SNAPSHOT and indeed the unnecessary dependencies are no longer there. Seems that keeping  class `Debug` is fine.

**Comment by cowtowncoder** [comment]
@kwin Thanks! I'll release 6.1.1 tonight then.

**Pull request merged**
