### PR TITLE
Try resolve #193: exclude refs to shaded modules

### LINKED ISSUE #193: Module `com.ctc.wstx` does not read a module that exports `com.ctc.wstx.shaded.msv.org_isorelax.verifier`
I'm getting the following error when running under JPMS (Java Modules) after upgrading 6.6.0

```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module com.ctc.wstx does not read a module that exports com.ctc.wstx.shaded.msv.org_isorelax.verifier
```

### PR DESCRIPTION
**Pull request by cowtowncoder**
Remove `provides` statements from module definition; hoping this resolves #193.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@pjfanning So basically, would this help avoid the issue?

**Comment by pjfanning** [comment]
seems to fix the broken test runs in POI - I'm running som extra tests - I'll get back when they complete

the JPM stuff is realy hard to get right and harder to test

**Comment by pjfanning** [comment]
the test run completed - seems like this might help - I hope it doesn't break something else - but so hard to know

**Comment by cowtowncoder** [comment]
@pjfanning Ok thanks! I think I should just go ahead and merge this, push a release. It's the only accumulated 6.6 change and if module stuff is not working it can't break worse (.. I hope).

**Pull request merged**
