### PR TITLE
Fix parser when not replacing entities and treating char references as entities

### PR DESCRIPTION
**Pull request by gnodet**
The problem is especially visible when configuring woodstox with round-tripping.
In this mode, char references and entities are not properly reported.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@gnodet Could you explain the problem in bit more detail (unless there's issue matching PR that has it)?
I know there are unit tests added (great!) but it's been a while so it'll take a while for me to remember logic wrt configuration settings.

**Comment by cowtowncoder** [comment]
Ah ok, thank you. That makes sense.

So `treatCharRefsAsEnts` is not taking effect in all combinations?

**Comment by gnodet** [comment]
> Ah ok, thank you. That makes sense.
> 
> So `treatCharRefsAsEnts` is not taking effect in all combinations?

It's actually worse than that.  It can cause wrong data to be returned when using `getLocalName()` for example.  That's how I found the problem.  This is shown in the test https://github.com/FasterXML/woodstox/pull/176/files#diff-47d3ee19006ff84cab043d2aeb042ff71d39c0ba4693aad07e822cddffa8631dR39, where the call to `getLocalName()` returns `foo` instead of `oelig` if you remove the fixes from this PR.

And yes, `treatCharRefsAsEnts` is also not taking effect when not replacing entities. This is shown in the test at line https://github.com/FasterXML/woodstox/pull/176/files#diff-0cacc0085dd6a986502abe8aacc2a6391f3093c33bcbfa38a5eb99f4de649fa0R127 which fails, the call to `next()` returning `CHARACTERS` instead of `ENTITY_REFERENCE`.

**Comment by cowtowncoder** [comment]
@gnodet Apologies for very slow follow up here. I'd be happy to merge this now.

But just one minor thing: if I haven't gotten CLA from you for Woodstox, I'd need it from:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

(yes, it's under Jackson repo but we use same CLA for Woodstox too).
It's easiest usually to print, fill & sign, scan/photo, email `cla` at fasterxml dot com.
This only needs to be done once, so if you had sent one earlier please let me know.
Otherwise looking forward to merging this contribution.

Thank you again!

**Comment by cowtowncoder** [comment]
Quick note wrt ^^^ -- CLA actually needs to go to `info` at fasterxml dot com.
So @gnodet if you sent one already it'd need to be re-sent. Apologies for mix up here.

**Comment by gnodet** [comment]
Resent to the correct address.

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Thank you again @gnodet ! I am hoping to get #174 (for #165) merged and can then release 6.6.0.

**Pull request merged**
