### PR TITLE
Extend XMLStreamWriter validation test coverage

### PR DESCRIPTION
**Pull request by ppalaga**
@cowtowncoder this is a preparation for the fix of #179: 

* Assert specific validation error messages to get more certainty that the expected error occurred
* Extend XMLStreamWriter validation test coverage by checking the writer validation wherever we test the reader validation

### CODE REVIEW

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Would be happy to merge this. Since there are non-test changes, one thing we need to have CLA (if not received yet, apologies if I missed it). One from Jackson repo:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

is one we use; it is usually easiest to print, fill & sign, scan/photo, email to `cla` at fasterxml dot com.

Once I have CLA it's good for all future contributions.

Looking forward to merging this, thank you!

**Comment by ppalaga** [comment]
>  we need to have CLA

I asked our legal team for an approval.

**Comment by cowtowncoder** [comment]
Thank you @ppalaga .

**Comment by cowtowncoder** [comment]
Since the only remaining changes here are test improvements, I can merge without CLA -- will do so.
(CLA needed for actual non-test code changes, just not test code)

**Comment by ppalaga** [comment]
@cowtowncoder our Legal team did not approve the [CLA](https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf) you pointed me to. The main concern lies in the broad scope of the copyright license, particularly with the request for joint ownership.
I wonder if I may let them review [the corporate CLA](https://github.com/FasterXML/jackson/blob/master/contributor-agreement-corporate.txt)?

**Comment by cowtowncoder** [comment]
Yes CCLA makes sense then. Have had a few company submit that, including some of FAANGs; no real difference for us.

**Pull request merged**
